services:
  mysql:
    image: mysql:8.3.0
    container_name: kwitch-mysql
    hostname: mysql
    ports:
      - "3306:3306"
    restart: "unless-stopped"
    environment:
      MYSQL_DATABASE: kwitch
      MYSQL_ROOT_PASSWORD: develop
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - kwitch-internal

  api-server:
    build: .
    container_name: kwitch-api-server
    hostname: api-server
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - kwitch-internal

networks:
  kwitch-internal:
