services: 
  redis:
    image: redis:7.2.0-alpine
    container_name: kwitch-redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal-network

  api-server:
    image: sukjuhong/kwitch-api-server:latest
    container_name: kwitch-api-server
    hostname: api-server
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - internal-network
      - proxy-network

networks:
  internal-network:
    driver: bridge
  proxy-network:
    external: true