services:
  postgres:
    image: postgres:16-alpine
    container_name: kwitch-postgres
    hostname: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal-network

  redis:
    image: redis:7.2.0-alpine
    container_name: kwitch-redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal-network

  api-server:
    image: sukjuhong/kwitch-server:latest
    container_name: kwitch-server
    hostname: server
    ports:
      - "8000:8000"
      - "40000-49999:40000-49999/tcp"
      - "40000-49999:40000-49999/udp"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - internal-network
      - proxy-network

networks:
  internal-network:
    driver: bridge
  proxy-network:
    external: true
